import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { EventFormProvider } from "./_components/contexts/event-form-context";
import { GuestFormProvider } from "./_components/contexts/guest-form-context";
import { type Viewport } from "next/types";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <EventFormProvider>
              <GuestFormProvider>{children}</GuestFormProvider>
            </EventFormProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
